spring.application.name=api-gateway
spring.config.import=configserver:http://config.platform:8888
eureka.client.service-url.defaultZone=http://vm-node-a.platform:8761/eureka,http://vm-node-b.platform:8761/eureka,http://vm-node-c.platform:8761/eureka
eureka.client.fetch-registry=true